/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CertificationUpdateManyWithoutUsersInput } from "./CertificationUpdateManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString, IsJSON } from "class-validator";
import { Type } from "class-transformer";
import { FormationUpdateManyWithoutUsersInput } from "./FormationUpdateManyWithoutUsersInput";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { WhiteTestUpdateManyWithoutUsersInput } from "./WhiteTestUpdateManyWithoutUsersInput";
@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CertificationUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CertificationUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CertificationUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  certifications?: CertificationUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => FormationUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => FormationUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => FormationUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  formations?: FormationUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: () => WhiteTestUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => WhiteTestUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => WhiteTestUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  whiteTests?: WhiteTestUpdateManyWithoutUsersInput;
}
export { UserUpdateInput };
