/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CertificationCreateNestedManyWithoutUsersInput } from "./CertificationCreateNestedManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString, IsJSON } from "class-validator";
import { Type } from "class-transformer";
import { FormationCreateNestedManyWithoutUsersInput } from "./FormationCreateNestedManyWithoutUsersInput";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { WhiteTestCreateNestedManyWithoutUsersInput } from "./WhiteTestCreateNestedManyWithoutUsersInput";
@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => CertificationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CertificationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CertificationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  certifications?: CertificationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  email!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => FormationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => FormationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => FormationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  formations?: FormationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: true,
  })
  @IsJSON()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => WhiteTestCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => WhiteTestCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => WhiteTestCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  whiteTests?: WhiteTestCreateNestedManyWithoutUsersInput;
}
export { UserCreateInput };
