/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Certification } from "../../certification/base/Certification";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  IsJSON,
} from "class-validator";
import { Type } from "class-transformer";
import { Formation } from "../../formation/base/Formation";
import { GraphQLJSON } from "graphql-type-json";
import { JsonValue } from "type-fest";
import { WhiteTest } from "../../whiteTest/base/WhiteTest";
@ObjectType()
class User {
  @ApiProperty({
    required: false,
    type: () => [Certification],
  })
  @ValidateNested()
  @Type(() => Certification)
  @IsOptional()
  certifications?: Array<Certification>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  email!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName!: string | null;

  @ApiProperty({
    required: false,
    type: () => [Formation],
  })
  @ValidateNested()
  @Type(() => Formation)
  @IsOptional()
  formations?: Array<Formation>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsJSON()
  @Field(() => GraphQLJSON)
  roles!: JsonValue;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => [WhiteTest],
  })
  @ValidateNested()
  @Type(() => WhiteTest)
  @IsOptional()
  whiteTests?: Array<WhiteTest>;
}
export { User };
