/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateFormationArgs } from "./CreateFormationArgs";
import { UpdateFormationArgs } from "./UpdateFormationArgs";
import { DeleteFormationArgs } from "./DeleteFormationArgs";
import { FormationFindManyArgs } from "./FormationFindManyArgs";
import { FormationFindUniqueArgs } from "./FormationFindUniqueArgs";
import { Formation } from "./Formation";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { FormationService } from "../formation.service";

@graphql.Resolver(() => Formation)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class FormationResolverBase {
  constructor(
    protected readonly service: FormationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Formation",
    action: "read",
    possession: "any",
  })
  async _formationsMeta(
    @graphql.Args() args: FormationFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Formation])
  @nestAccessControl.UseRoles({
    resource: "Formation",
    action: "read",
    possession: "any",
  })
  async formations(
    @graphql.Args() args: FormationFindManyArgs
  ): Promise<Formation[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Formation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Formation",
    action: "read",
    possession: "own",
  })
  async formation(
    @graphql.Args() args: FormationFindUniqueArgs
  ): Promise<Formation | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Formation)
  @nestAccessControl.UseRoles({
    resource: "Formation",
    action: "create",
    possession: "any",
  })
  async createFormation(
    @graphql.Args() args: CreateFormationArgs
  ): Promise<Formation> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Formation)
  @nestAccessControl.UseRoles({
    resource: "Formation",
    action: "update",
    possession: "any",
  })
  async updateFormation(
    @graphql.Args() args: UpdateFormationArgs
  ): Promise<Formation | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Formation)
  @nestAccessControl.UseRoles({
    resource: "Formation",
    action: "delete",
    possession: "any",
  })
  async deleteFormation(
    @graphql.Args() args: DeleteFormationArgs
  ): Promise<Formation | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [User])
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async user(
    @graphql.Parent() parent: Formation,
    @graphql.Args() args: UserFindManyArgs
  ): Promise<User[]> {
    const results = await this.service.findUser(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
